import { Flex, Grid, Rating, Switch, Text } from "@mantine/core";

interface RatingsProps {
    value?: { [key: string]: number };
    onChange?: (value: { [key: string]: number }) => void;
}

const questions = [
    {
        preface: "Regarding the clarity of the question, it was",
        value: "clarity",
        1: "Very hard to understand",
        5: "Very easy to understand",
    },
    {
        preface: "Regarding the helpfulness of the question, it was",
        value: "helpfulness",
        1: "Not helpful for understanding coding concepts.",
        5: "Very helpful for understanding coding concepts.",
    },
];

const Ratings: React.FC<RatingsProps> = ({ value, onChange }) => {
    return (
        <Grid>
            <Grid.Col span={8}>
                Did the code seem like it was generated by AI? Did it use any
                methods or syntax that wasn't covered in class?
            </Grid.Col>
            <Grid.Col span={4}>
                <Flex justify="center" align="center">
                    <Switch
                        onChange={(event) => {
                            const checked = event.currentTarget.checked;
                            const newValue = {
                                ...value,
                                ["ai-usage"]: checked ? 1 : 0,
                            };
                            onChange && onChange(newValue);
                        }}
                        onLabel="Yes"
                        offLabel="No"
                        checked={value ? value["ai-usage"] == 1 : false}
                    />
                </Flex>
            </Grid.Col>
            {questions.map((question) => {
                return (
                    <>
                        <Grid.Col span={4}>
                            <Text>{question.preface}</Text>
                        </Grid.Col>
                        <Grid.Col span={8}>
                            <Flex justify="center" align="center" gap="md">
                                <Text size="sm">{question[1]}</Text>
                                <Rating
                                    value={
                                        value
                                            ? value[question.value]
                                            : undefined
                                    }
                                    onChange={(val) => {
                                        const newValue = {
                                            ...value,
                                            [question.value]: val,
                                        };
                                        onChange && onChange(newValue);
                                    }}
                                    count={5}
                                />
                                <Text size="sm">{question[5]}</Text>
                            </Flex>
                        </Grid.Col>
                    </>
                );
            })}
        </Grid>
    );
};

export default Ratings;
